apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stigmergic-mesh-router.fullname" . }}-secret
  labels:
    {{- include "stigmergic-mesh-router.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: ""
  {{- if .Values.security.enabled }}
  tenant-keys: {{ .Values.security.defaultTenantKeys | default list | toJson | b64enc }}
  {{- end }}
